### ISSUE TITLE
Weekly Scrum - week 2

### ISSUE THREAD

**Issue by jaymccracken** [EveningStarlight/SYSC_4806_Project#24]

**Comment by jaymccracken** [comment]
Heroku is hard to configure, we need to rescope
Tried: create database on heroku and query db through php; issue: heroku cant deploy nodejs and php

**Comment by mattman555** [comment]
Tried and failed to set up postgresql data base on heroku. This lead to failures.
Set up a JSON back end that can be read and wrote too at least to be temporary so that there is a back end to be functional for the front end.
what will I do next week?
look further into setting up a persistent file store #29 
Create Survey Button Functionality #12 
Create page that receives created survey #6 
What is holding me back?
ran into issues with php and heroku not working found out it is the that php needs to be deployed separately this won't work. Had issues getting form data and writing it to data files.

**Comment by EveningStarlight** [comment]
## This week

designed landing page and navigation #3 
Added the ability to add questions to the survey #7 
added the ability to remove questions from the survey #30
Looked for solutions to solving #4, no solution arose from this.

## Next Week

Add support for #12 
Add different types of questions #34
Create a survey to fill out dynamically #10 

## Difficulties

Database support ate up a lot of our development time. #4
The dynamic questions were updating the array of questions, but new components were not being rendered. #7

**Comment by imran1503** [comment]
This week:
I created the surveyor's homepage   #8

Next week:
I plan to have the homepage pull up all of the users surveys dynamically #8 
I also plan to add the links to view each table. #9

Difficulties:
We had trouble getting the database deployed and I personally struggled with learning the react version of JavaScript.
