### ISSUE TITLE
Weekly Scrum - Week 3 (14th-18th)

### ISSUE THREAD

**Issue by jaymccracken** [EveningStarlight/SYSC_4806_Project#43]

**Comment by imran1503** [comment]
Continued working on reading all database entries.

**Comment by jaymccracken** [comment]
What i did:
Formatted the create survey form on submit to be a json format on submit, ready to written to the db.json when ready. (https://github.com/EveningStarlight/SYSC_4806_Project/issues/13) 

What i want to do next:
work on taking the answers and formatting it into a json and submit adding it to the end of the survey in the db.json. create the front end pages for when survey is submitted. (https://github.com/EveningStarlight/SYSC_4806_Project/issues/44)(https://github.com/EveningStarlight/SYSC_4806_Project/issues/13) 

what is blocking me:
4th year project is wrapping up so spent a lot of time on that this week. and waiting for the db.json to be set up properly

**Comment by EveningStarlight** [comment]
## This week

Designed the implementation of different questions (text, number, choice)
Includes the ability to add and remove questions from the list #34 
Improved the numbering of questions by implementing an ordered list #41 
Gave advice for saving survey as a JSON #13 

## Next Week

Create a survey dynamically from the given JSON #10 


## Difficulties

Rendering the question list was difficult because React was not recognizing that the arrays were being changed, so wasn't rerendering. A sub component that contains a prop for the questions helped to fix this.
Being able to create multiple options for the choice question was difficult.
Having the components be able to get their json to the parent on submit was not easy to figure out.
